### ISSUE TITLE
same as morph-starter issue #1. module not found: com.typesafe.sbteclipse#sbteclipse-plugin;2.1.2

### ISSUE THREAD

**Issue by mgaldzic** [jpcik/morph#1]
looks like the same issue as morph-starter issue #1 at https://github.com/jpcik/morph-starter/issues/1#issuecomment-27042199

**Comment by jpcik** [comment]
indeed, morph has been built with sbt 0.12.
to check your sbt-version: sbt sbt-version

will move to sbt 0.13 anytime soon. assigned to me.

**Comment by jpcik** [comment]
changed to sbt 0.13 and sbteclipse-plugin;2.4.0
