### ISSUE TITLE
subjectMap template string concatenation in SQL server

### ISSUE THREAD

**Issue by seralf** [jpcik/morph#2]
Hi I'm trying to use the library on _SQL Server_.

Starting from a view like:

> SELECT T.ID AS id, FROM myTable AS T;

and using in the subject mapping:

> rr:subjectMap [ rr:template "{\"id\"}" ]; 

the generated query has the following structure:

> query SELECT ('' || TABLE1."id") AS subject FROM (SELECT T.ID AS id
> FROM myTable AS T) TABLE1 

and gives me the error:

> Exception in thread "main" es.upm.fi.oeg.morph.execute.RelationalQueryException: Invalid query: Incorrect syntax near '|'. at es.upm.fi.oeg.morph.execute.RdfGenerator$$anonfun$2.apply(RdfGenerator.scala:130)
> [...]

i don't know why the stacktrace is reporting line 130 :-) , but the problem seems to be in RdbQueryGenerator.formatTemplate() method.

The method internally uses the standard concatenation operator, and it is not supported by SQL Server dialect.

An alternative for SQL Server in this case would be generate something like: 

> SELECT ('http://localhost/' + CONVERT(varchar(8), T.ID, 101)) AS id

A good general workaround could be in introducing some system-wide variable to trace what dialect we are currently using, in order to translate for a specific platform

TIP: Generating the concatenation from the SQL View and then using a rr:column mapping is instead correctly working.

**Comment by jpcik** [comment]
Thanks, this is true, we are using that sort of concat syntax. We have not tried this in sQL Server

**Comment by jpcik** [comment]
and it is still open

**Comment by seralf** [comment]
Hi, I have made a pull request on this:
https://github.com/jpcik/morph/pull/7

In order to resolve my problems with sqlserver without changing too much the current behaviour, I have introduced a couple of parameters and case classes. The implementation could be written in a more flexible way with some refactorization.

**Comment by seralf** [comment]
seems resolved in the last updates, thanks
