### ISSUE TITLE
sbt: URI has an authority component error

### ISSUE THREAD

**Issue by seralf** [jpcik/morph#3]
Hi

while trying to execute 

> sbt update
> sbt compile

I get the following error:

`
sbt.ResolveException: unresolved dependency: ch.qos.logback#logback-classic;1.0.13: several problems occurred while resolving dependency: ch.qos.logback#logback-classic;1.0.13 {test=[default(compile)]}:
        several problems occurred while resolving dependency: ch.qos.logback#logback-parent;1.0.13 {}:
        URI has an authority component
    [...]
[error] (morph-core/*:update) sbt.ResolveException: unresolved dependency: ch.qos.logback#logback-classic;1.0.13: several problems occurred while resolving dependency: ch.qos.logback#logback-classic;1.0.13 {test=[default(compile)]}:
[error]         several problems occurred while resolving dependency: ch.qos.logback#logback-parent;1.0.13 {}:
[error]         URI has an authority component
`

I have also tried to update the reference to a newer version of logback without luck.
I am testing this on win7, with latest scala and sbt.

**Comment by jpcik** [comment]
This is most likely an open bug in sbt 0.13.1 (in windows): https://github.com/sbt/sbt/issues/1086

A workaround is to use sbt 0.13.0:
so unisntalling sbt and using the previous version:
http://www.scala-sbt.org/0.13.0/docs/Getting-Started/Setup.html

**Comment by seralf** [comment]
uhm thank you, I didn't find this reference! I suppose this should be
strange

2014-02-21 18:21 GMT+01:00 Jean-Paul Calbimonte notifications@github.com:

**Comment by seralf** [comment]
ok the problem seems to be with two different part of the configuration file:

resolvers ++= Seq( DefaultMavenRepository, "Local ivy Repository" at "file://"+Path.userHome.absolutePath+"/.ivy2/local")

val publishSettings = Seq (
        publishTo := Some("Artifactory Realm" at "http://aldebaran.dia.fi.upm.es/artifactory/sstreams-releases-local"),
        credentials += Credentials(Path.userHome / ".ivy2" / ".credentials"),
        publishMavenStyle := true,
        publishArtifact in (Compile, packageSrc) := false )

disabling those, all seems to correctly work

##### UPDATE

I was using git shell for windows.
Doing a simple git clone / compile etc from scratch with windows command line does not give me any error instead... very weird :-/

**Comment by tgkprog** [comment]
Still get this on windows 7. Used clone of 23 sep 2015. 
Using
1. java "1.6.0_45"
2. Scala code runner version 2.10.5
3. sbt 0.13.0 from jar 
4. [info] scalding/*:version
[info]  0.15.1-SNAPSHOT
5. tried with windows cmd.exe shell and the git shell.

On git shell tried ./sbt compile

on windows shell tried by calling batch program with sbt jar (version 13.0), earlier also tried with installed sbt (latest)
